# HW01: Các câu lệnh Linux, Python

(Cập nhật lần cuối 12/10/2025)

Họ tên: Nguyễn Hải Đăng

MSSV: 23127165

---

## Cách làm bài và nộp bài

&#9889; Bạn lưu ý là mình sẽ dùng chương trình hỗ trợ chấm bài nên bạn cần phải tuân thủ chính xác qui định mà mình đặt ra, nếu không rõ thì hỏi, chứ không nên tự tiện làm theo ý của cá nhân.

**Cách làm bài**

Bạn sẽ làm trực tiếp trên file notebook này. Đầu tiên, bạn điền họ tên và MSSV vào phần đầu file ở bên trên. Trong file, bạn làm bài ở những chỗ có ghi là:
```python
# YOUR CODE HERE
raise NotImplementedError()
```
hoặc đối với những phần code không bắt buộc thì là:
```python
# YOUR CODE HERE (OPTION)
```
hoặc đối với markdown cell thì là:
```markdown
YOUR ANSWER HERE
```
Tất nhiên, khi làm thì bạn xóa dòng `raise NotImplementedError()` đi.
Đối những phần yêu cầu code thì thường ở ngay phía dưới sẽ có một (hoặc một số) cell chứa các bộ test để giúp bạn biết đã code đúng hay chưa; nếu chạy cell này không có lỗi gì thì có nghĩa là qua được các bộ test. Trong một số trường hợp, các bộ test có thể sẽ không đầy đủ; nghĩa là, nếu không qua được test thì là code sai, nhưng nếu qua được test thì chưa chắc đã đúng hoàn toàn.

Trong khi làm bài, bạn có thể cho in ra màn hình, tạo thêm các cell để test. Nhưng khi nộp bài thì bạn xóa các cell mà bạn tự tạo, xóa hoặc comment các câu lệnh in ra màn hình. Bạn lưu ý <font color=red>không được tự tiện xóa các cell hay sửa code của Thầy</font> (trừ những chỗ được phép sửa như đã nói ở trên).

Bạn cố gắng giữ cho code rõ ràng, ngăn nắp: đặt tên biến gợi ý, comment ở những chỗ cần comment, giữ cho một dòng code không quá dài (vì nếu không thì người đọc sẽ phải mất công scroll, bạn có thể dùng qui tắc: một dòng code chỉ nên có tối đa là 79 ký tự). 

Trong khi làm bài, thường xuyên `Ctrl + S` để lưu lại bài làm của bạn, tránh mất mát thông tin.


*Nên nhớ mục tiêu chính ở đây là <font color=green>học, học một cách chân thật</font>. Bạn có thể thảo luận ý tưởng với bạn khác, nhưng <font color=green>code và bài làm phải là của bạn, dựa trên sự hiểu thật sự của bạn</font>. <font color=red>Nếu vi phạm thì sẽ bị 0 điểm cho toàn bộ môn học.</font>*

**Cách nộp bài**

Khi chấm bài, đầu tiên mình sẽ chọn `Kernel` - `Restart & Run All` để restart và chạy tất cả các cell trong notebook của bạn; do đó, trước khi nộp bài, bạn nên chạy thử `Kernel` - `Restart & Run All` để đảm bảo mọi chuyện diễn ra đúng như mong đợi.

Sau đó, bạn tạo thư mục nộp bài theo cấu trúc sau:
- Thư mục `MSSV` (vd, nếu bạn có MSSV là 1234567 thì bạn đặt tên thư mục là `1234567`)
    - File `HW01.ipynb` (không cần nộp các file khác)

Cuối cùng, bạn nén thư mục `MSSV` này lại và nộp ở link trên moodle. <font color=red>Bạn lưu ý tuân thủ chính xác qui định nộp bài.</font>

---

## Môi trường code

Ta thống nhất trong môn này:
- Code trên môi trường Linux (bạn đã setup ở HW0)
- Dùng Jupyter Notebook hoặc Jupyter Lab để code file .ipynb. Lưu ý: bạn <font color=red>không dùng Google Colab</font>, vì Google Colab có thể xóa một số thông tin meta mà chương trình hỗ trợ chấm bài của mình đã tạo trong file bài tập
- Dùng phiên bản các package như trong file "min_ds-env.yml" (bạn xem trong HW0 cách dùng Conda để tạo môi trường code từ file .yml và cách kích hoạt môi trường này sau khi đã tạo)

In [1]:
import sys
sys.executable

'/Users/dangnguyen/miniconda3/envs/min_ds-env/bin/python'

Nếu không có vấn đề gì thì file chạy python sẽ là file của môi trường code "min_ds-env".

Trong bài này, ngoài Git & Jupyter Notebook/Lab thì bạn chỉ dùng Python, không dùng các thư viện khác như Numpy, Pandas, ... Trong Python, khi đọc/ghi file csv thì bạn cũng không được dùng các thư viện hỗ trợ như thư viện `csv`.

---

## Import các thư viện cần thiết

In [2]:
import datetime
import os

---

## Thu thập dữ liệu (3.5đ)

Trong bài tập này, bạn sẽ lấy dữ liệu log của [thùng chứa nbdime](https://github.com/namlnhut/nbdime). Nbdime là công cụ giúp Git có thể diff và merge file Notebook một cách phù hợp (thay vì chỉ coi như là một file text thông thường). Link mình cung cấp không phải là link đến thùng chứa gốc của nbdime mà là thùng chứa mình "fork" (đại khái là tạo ra một bản copy) từ thùng chứa gốc. Lý do: mình muốn cố định lại dữ liệu log để có thể cung cấp các bộ test để bạn phần nào biết là đã code đúng hay chưa (còn nếu dùng thùng chứa gốc thì dữ liệu log có thể sẽ thay đổi trong vài ngày tới, các bộ test lúc đó có thể sẽ không còn đúng nữa).

Để có thể lấy dữ liệu log thì việc đầu tiên bạn cần làm ở cell bên dưới là: 

- Dùng câu lệnh Git để clone thùng chứa về; bạn clone vào một thư mục cùng cấp với file notebook này. <font color=gray>Gợi ý: trong Jupyter Notebook, ở code cell, bạn có thể thực hiện một câu lệnh Linux (bao gồm câu lệnh Git) bằng cách thêm dấu ! ở đầu.</font>
- Sau đó, để xem thử thư mục vừa clone có nặng không, bạn tính dung lượng tổng cộng của thư mục này và lưu vào biến `repo_size` (`repo_size` là một con số, đơn vị là MB); ta thống nhất: (i) dùng cờ `--apparent-size` khi dùng câu lệnh `du`, (ii) code chỉ cần chạy đúng với thùng chứa cụ thể này. <font color=gray>Gợi ý: trong Jupyter Notebook, bạn có thể gán kết quả của câu lệnh Linux vào biến Python.</font> \
@ Các bạn dùng Mac: trong Mac thì mình nghe nói là câu lệnh `du` không có cờ `--apparent-size` (do câu lệnh `du` của Mac là bản BSD, còn của Linux là bản GNU); bạn có thể xem thử cách cài câu lệnh `du` bản GNU ở [video này](https://youtu.be/VGgTmxXp7xQ?t=894) (trong video là nói về câu lệnh `grep` nhưng mình nghĩ cũng sẽ tương tự với câu lệnh `du`).

In [3]:
# YOUR CODE HERE
repo_url = "https://github.com/namlnhut/nbdime.git"
repo_dir = "nbdime"

# 1. Clone repo về
if not os.path.exists(repo_dir):
    !git clone {repo_url} {repo_dir}

# 2. Tính dung lượng tổng cộng của thư mục (theo đơn vị MB)
# Dùng du -sb --apparent-size để lấy kích thước bytes, sau đó chia cho (1024 * 1024)
try:
    # Lấy kích thước bytes bằng GNU du
    du_output = !du -sb --apparent-size {repo_dir}
    size_bytes_str = du_output[0].split('\t')[0].strip()
    size_bytes = int(size_bytes_str)
except Exception:
    # Fallback: dùng du -s (KB) cho BSD/Mac và chuyển đổi
    du_output = !du -s {repo_dir}
    size_kB_str = du_output[0].split('\t')[0].strip()
    size_bytes = int(size_kB_str) * 1024 # KB -> Bytes

repo_size = size_bytes / (1024 * 1024)
print(f"The size of this repo is {repo_size} MB") 

The size of this repo is 45.3828125 MB


Sau khi đã clone thùng chứa về, việc kế tiếp của bạn là dùng các câu lệnh Linux (trong đó có các câu lệnh Git) và Python để lấy dữ liệu log rồi lưu xuống file "log.tsv" (định dạng tsv tương tự như csv nhưng các giá trị được cách nhau bởi tab). Để dễ hình dung, bạn có thể dùng Jupyter Lab để mở xem file kết quả đúng "correct_log.tsv" mà mình cung cấp. Như bạn có thể thấy, mỗi dòng ứng với một commit (không tính dòng đầu - dòng chứa các tên cột) và gồm các thông tin:
- "Id" là id (hash) dạng viết gọn của commit
- "ParentIds" là id dạng viết gọn của (các) commit cha
- "AuthorName" là tên của tác giả
- "AuthorEmail" là email của tác giả
- "AuthorDate" là ngày tác giả thực hiện commit, ngày được format theo chuẩn RFC2822 (xem phần gợi ý ở bên dưới để biết cách lấy ngày theo format này) 
- "Subject" là tựa đề của message (message tương tự như email, ngoài phần "subject" thì có thể có thêm phần "body"; ở đây ta chỉ lấy phần "subject")
- "ChangedFiles": các file bị thay đổi, nếu có nhiều file thì các file được phân tách bởi dấu phẩy

Tại sao mình dùng định dạng tsv thay vì csv? Vì dấu phẩy nhiều khả năng là sẽ có trong phần "subject" của message. Tab ít khả năng sẽ có hơn, nhưng nếu có thì bạn hãy thay bằng bốn khoảng trắng.

<font color=gray>Gợi ý cho phần này:</font> 
- <font color=gray>Bạn có thể xem thêm về câu lệnh `git log` [ở đây](https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History)</font>
- <font color=gray>Khi ở Notebook, bạn thử `cd` đến thư mục clone rồi `pwd` xem? Kết quả như vậy là vì khi thực hiện một dòng lệnh Linux ở Notebook thì Notebook sẽ tạo ra một terminal tạm thời để thực thi dòng lệnh đó trong phút chốc. Như vậy, câu lệnh `cd` vẫn là có `cd` đến thư mục clone nhưng là ở terminal tạm thời; khi câu lệnh `cd` chạy xong thì terminal tạm thời này sẽ được đóng và ta vẫn ở thư mục mà hiện chứa file Notebook. Để có thể `cd` rồi `pwd` thì một cách là ghi 2 câu lệnh này trên một dòng và cách nhau bởi `&&`; lúc này thì cả 2 câu lệnh sẽ được thực thi trên cùng một terminal</font>

In [4]:
# YOUR CODE HERE
# 1. Lấy dữ liệu log
# Dùng "||" làm separator để dễ dàng tách metadata commit
# %h: Id, %p: ParentIds, %an: AuthorName, %ae: AuthorEmail, %ad: AuthorDate (RFC2822), %s: Subject
log_output = !cd nbdime && git log --pretty=format:"%h||%p||%an||%ae||%ad||%s" --date=rfc2822 --name-only

commits = []
current = None

# 2. Phân tích dữ liệu log
for line in log_output:
    line = line.strip()
    
    if not line:
        # Xử lý kết thúc một commit block
        if current is not None:
            # Gộp danh sách file thành chuỗi ngăn cách bởi dấu phẩy
            current["ChangedFiles"] = ",".join(current["ChangedFiles"])
            commits.append(current)
            current = None
        continue

    if '||' in line:
        # Xử lý dòng metadata commit
        if current is not None:
            # Xử lý commit trước nếu chưa được thêm (lỗi logic nhỏ)
            current["ChangedFiles"] = ",".join(current["ChangedFiles"])
            commits.append(current)
        
        parts = line.split("||", 5) # Giới hạn split để giữ Subject nguyên vẹn
        
        # Yêu cầu: thay thế tab trong Subject bằng 4 khoảng trắng
        subject = parts[5].replace('\t', '    ')
        
        current = {
            "Id": parts[0],
            "ParentIds": parts[1],
            "AuthorName": parts[2],
            "AuthorEmail": parts[3],
            "AuthorDate": parts[4],
            "Subject": subject,
            "ChangedFiles": []
        }
    else:
        # Xử lý dòng tên file thay đổi
        if current is not None:
            current["ChangedFiles"].append(line)

# Xử lý commit cuối cùng
if current is not None:
    current["ChangedFiles"] = ",".join(current["ChangedFiles"])
    commits.append(current)

# 3. Ghi ra file log.tsv
file = open("log.tsv", 'w', encoding='utf-8')
header = ["Id", "ParentIds", "AuthorName", "AuthorEmail", "AuthorDate", "Subject", "ChangedFiles"]
file.write("\t".join(header) + "\n")
for commit in commits:
    # Đảm bảo tất cả các giá trị được ghi ra file (Subject đã được xử lý tab)
    row = [commit[h] for h in header]
    file.write("\t".join(row) + "\n")
file.close()

In [5]:
# TEST
file = open('log.tsv', 'r')
log = file.read()
file.close()
file = open('correct_log.tsv', 'r')
correct_log = file.read()
file.close()
assert log == correct_log

---

## Khám phá dữ liệu

### Dữ liệu có bao nhiêu dòng và bao nhiêu cột? (0.5đ)

Đầu tiên, bạn sẽ đọc dữ liệu từ file "log.tsv" (nếu phần thu thập dữ liệu bạn làm chưa đúng thì bạn có thể đọc từ file "correct_log.tsv" mà mình đã cung cấp). Bạn lưu kết quả đọc được vào biến `cols`. Biến `cols` là một dictionary, trong đó mỗi phần tử ứng với một cột, key là chuỗi ứng với tên cột, value là list chứa các giá trị của cột (mỗi giá trị bạn cứ tạm để kiểu dữ liệu là chuỗi).

Kế tiếp, từ biến `cols`, bạn sẽ tính số dòng và số cột, rồi lần lượt lưu vào hai biến là `num_rows` và `num_cols`.

In [6]:
# YOUR CODE HERE
file = open('log.tsv', 'r', encoding='utf-8')
log = [line.strip('\n') for line in file.readlines()]
file.close()

# Trích xuất header và khởi tạo cols dictionary
header = log[0].split('\t')
cols = {h: [] for h in header}

# Xử lý các dòng dữ liệu (bỏ qua header và các dòng trống)
data_lines = [line for line in log[1:] if line.strip()]

for line in data_lines:
    parts = line.split('\t')
    
    # Đảm bảo gán giá trị cho tất cả các cột
    for i, h in enumerate(header):
        val = parts[i] if i < len(parts) else '' # Dùng '' cho các giá trị thiếu
        cols[h].append(val)
        
num_rows = len(next(iter(cols.values())))
num_cols = len(cols)

In [7]:
# TEST
assert num_rows == 2149
assert num_cols == 7
assert set(cols.keys()) == set(['Id', 'ParentIds', 'AuthorName', 
                                'AuthorEmail', 'AuthorDate', 'Subject', 
                                'ChangedFiles'])
id_col_len = len(cols['Id'])
for col_name in cols:
    assert len(cols[col_name]) == id_col_len

### Mỗi dòng có ý nghĩa gì? Có vấn đề các dòng có ý nghĩa khác nhau không?

Mỗi dòng ứng với một commit. Có vẻ không có dòng nào "lạc loài" (nghĩa là không có vấn đề các dòng có ý nghĩa khác nhau).

### Dữ liệu có các dòng bị lặp không? (0.25đ)

Có lẽ là không có. Để chắc ăn thì một cách là ta có thể check cột "Id"; nếu cột "Id" không có giá trị bị lặp thì có thể kết luận là không có dòng bị lặp. Bạn sẽ làm vụ này và lưu kết quả check vào biến `duplicated_id`; biến này bằng True nếu cột "Id" có giá trị lặp và bằng False nếu ngược lại.

In [8]:
# YOUR CODE HERE
ids = cols['Id']
duplicated_id = len(ids) != len(set(ids))

In [9]:
# TEST
assert duplicated_id == False

### Mỗi cột có ý nghĩa gì?

Vụ này mình đã nói lúc thu thập dữ liệu. Ở đây, mình ghi lại một lần nữa:

- "Id" là id (hash) dạng viết gọn của commit
- "ParentIds" là id dạng viết gọn của (các) commit cha
- "AuthorName" là tên của tác giả
- "AuthorEmail" là email của tác giả
- "AuthorDate" là ngày tác giả thực hiện commit
- "Subject" là tựa đề của message (message tương tự như email, ngoài phần "subject" thì có thể có thêm phần "body"; ở đây ta chỉ lấy phần "subject")
- "ChangedFiles": các file bị thay đổi, nếu có nhiều file thì các file được phân tách bởi dấu phẩy

### Mỗi cột hiện đang có kiểu dữ liệu gì? Có cột nào có kiểu dữ liệu chưa phù hợp để có thể xử lý tiếp không?

- Các cột "Id", "ParentIds", "AuthorName", "AuthorEmail", "Subject": kiểu dữ liệu dạng chuỗi là đúng rồi
- Cột "ChangedFiles": hmm ... có lẽ tạm thời ta vẫn để dạng chuỗi, có gì cần thì ta sẽ xử lý sau
- Cột "AuthorDate": cần chuyển từ kiểu dữ liệu dạng chuỗi sang datetime; để có thể tiếp tục khám phá tiếp thì ngay sau đây bạn sẽ tiền xử lý vụ này luôn

---

## Tiền xử lý (0.5đ)

Ở đây, bạn sẽ chuyển cột "AuthorDate" từ dạng chuỗi sang datetime. <font color=gray>Gợi ý: bạn xem [document](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) để biết cách truyền format phù hợp cho hàm `strptime`.</font>

In [10]:
# YOUR CODE HERE
# Định dạng RFC2822: '%a, %d %b %Y %H:%M:%S %z'
date_format = '%a, %d %b %Y %H:%M:%S %z'

# Chuyển đổi cột AuthorDate sang datetime.datetime
# Do log output đảm bảo có ngày, nên ta có thể dùng list comprehension đơn giản
cols['AuthorDate'] = [datetime.datetime.strptime(s, date_format) for s in cols['AuthorDate']]

In [11]:
# TEST
assert type(cols['AuthorDate'][0]) == datetime.datetime
assert cols['AuthorDate'][0] == datetime.datetime(2025, 10, 9, 11, 32, 46, 
            tzinfo=datetime.timezone(datetime.timedelta(seconds=7200)))

---

## Khám phá dữ liệu (tiếp tục)

### Với mỗi cột có kiểu dữ liệu dạng số (numeric) và dạng datetime, các giá trị được phân bố như thế nào? (0.5đ)

Ở đây thì không có cột dạng số, chỉ có một cột dạng datetime là cột "AuthorDate".

Đầu tiên, bạn tính tỉ lệ % các giá trị thiếu của cột "AuthorDate". <font color=gray>Gợi ý: không cần code, có thể lập luận dựa vào kết quả khi chuyển cột "AuthorDate" từ dạng chuỗi sang datetime ở bên trên.</font>

YOUR ANSWER HERE

=> Khi chuyển từ chuỗi sang `datetime` bằng `strptime` như đã làm, mọi giá trị đều được chuyển đổi thành công (vì dữ liệu log đảm bảo có ngày), do đó, tỉ lệ % các giá trị thiếu của cột "AuthorDate" là **0.000%**.

Tiếp theo, bạn tính min và max của cột "AuthorDate", rồi lần lượt lưu vào hai biến `author_date_min` và `author_date_max`.

In [12]:
# YOUR CODE HERE
author_date_min = min(cols['AuthorDate'])
author_date_max = max(cols['AuthorDate'])

In [13]:
# TEST
assert author_date_min == datetime.datetime(2015, 11, 9, 13, 13, 28, 
            tzinfo=datetime.timezone(datetime.timedelta(seconds=3600)))
assert author_date_max == datetime.datetime(2025, 10, 9, 11, 32, 46, 
            tzinfo=datetime.timezone(datetime.timedelta(seconds=7200)))

Hmm ... Min và max của cột "AuthorDate" không có gì bất thường.

### Với mỗi cột có kiểu dữ liệu dạng phân loại (categorical), các giá trị được phân bố như thế nào? (1.75đ)

Các cột dạng phân loại là các cột mà không phải là cột "AuthorDate". Bạn sẽ lưu thông tin của các cột này vào biến `cate_col_profiles`. Biến này là một dictionary, trong đó mỗi phần tử ứng với một cột dạng phân loại, key là tên cột, value là list gồm: tỉ lệ % giá trị thiếu, số lượng các giá trị khác nhau (không tính giá trị thiếu), set chứa các giá trị khác nhau (không bao gồm giá trị thiếu).

In [14]:
# YOUR CODE HERE
cate_col_profiles = {}
categorical_cols = [col for col in cols if col != 'AuthorDate']

for col_name in categorical_cols:
    col_data = cols[col_name]
    
    # 1. Tỉ lệ % giá trị thiếu (empty string '')
    missing_count = sum(1 for val in col_data if val == '')
    missing_percentage = (missing_count / len(col_data)) * 100
    
    # 2. & 3. Get unique non-missing values
    unique_vals = {val for val in col_data if val != ''}
    num_unique_vals = len(unique_vals)
    
    # Store results
    cate_col_profiles[col_name] = [
        missing_percentage,
        num_unique_vals,
        unique_vals
    ]

In [15]:
# TEST
assert set(cate_col_profiles.keys()) == {'AuthorEmail', 'AuthorName', 
                                         'ChangedFiles', 'Id', 
                                         'ParentIds', 'Subject'}
for col_name, col_profile in cate_col_profiles.items():
    assert len(col_profile) == 3
    assert len(col_profile[2]) == col_profile[1]
assert round(cate_col_profiles['ParentIds'][0], 3) == 0.047
assert round(cate_col_profiles['ChangedFiles'][0], 3) == 15.914
assert cate_col_profiles['ParentIds'][1] == 2029
assert cate_col_profiles['ChangedFiles'][1] == 934

In [16]:
# TEST (BY EYES)
print(f"{'ColName':12} {'Miss(%)':7} {'NumDifVals':10} {'SomeVals'}")
for col_name, col_profile in cate_col_profiles.items():
    print(f'{col_name:12} {col_profile[0]:<7.3f} {col_profile[1]:<10} {col_profile[2].__repr__()[:34]+"...":<}')

ColName      Miss(%) NumDifVals SomeVals
Id           0.000   2149       {'b806cae', '3b00a74', '9f8ef0f', ...
ParentIds    0.047   2029       {'b806cae', '3b00a74', '9f8ef0f', ...
AuthorName   0.000   55         {'Daniel Mietchen', 'Todd', 'githu...
AuthorEmail  0.000   58         {'91276442+kr0p07k1n@users.noreply...
Subject      0.000   2058       {'Test with both jupyter_server 2 ...
ChangedFiles 15.914  934        {'nbdime/tests/test_diff_json_conv...


Bạn quan sát kết quả in ra ở trên (tạm thời chưa để ý đến cột "Miss(%)") và cho biết có gì bất thường không? Hay mọi thứ đều bình thường? Cho mình biết tại sao bạn lại kết luận như vậy.

YOUR ANSWER HERE:

=> *Mọi thứ đều **bình thường** (Normal)*

* **Id:** Số lượng giá trị khác nhau (**2149**) bằng tổng số dòng (**2149**), xác nhận tính **duy nhất** của commit ID.

* **AuthorName/AuthorEmail:** Số lượng tên (**55**) và email (**58**) khác nhau nhỏ hơn tổng số dòng là điều **bình thường** (vì cùng một người đóng góp thực hiện nhiều commit). Việc số lượng **Email (58) nhiều hơn Tên (55)** cũng là **bình thường** trong môi trường Git thực tế, do một tác giả có thể sử dụng **nhiều địa chỉ email** khác nhau (công việc, cá nhân, bot) cho các commit của họ.

* **ParentIds (2029)** và **Subject (2058)** có số lượng giá trị khác nhau gần bằng tổng số dòng. Điều này cho thấy tính đa dạng cao và phù hợp với lịch sử Git:
    * `ParentIds` khác nhau ít hơn vì nhiều commit có thể chia sẻ cùng commit cha.
    * `Subject` khác nhau ít hơn vì một số commit có thể có tiêu đề trùng lặp (thường là commit tự động hoặc commit nhỏ).

* **ChangedFiles (934)** có số lượng giá trị khác nhau ít hơn tổng số dòng là điều **bình thường**, vì nhiều commit có thể thay đổi cùng một nhóm file hoặc không thay đổi file nào (như các merge commit, chiếm khoảng 16% giá trị thiếu).

Kế tiếp, bạn hãy cho in ra các dòng mà có giá trị thiếu (in sao là tùy bạn, miễn là dễ nhìn). Sau đó, bạn hãy quan sát các dòng này để xem tại sao lại bị thiếu (trong trường hợp, bạn không biết tại sao thì cứ ghi nhận là không biết tại sao).

In [17]:
# YOUR CODE HERE
header_to_print = ['Id', 'ParentIds', 'AuthorName', 'AuthorDate', 'Subject', 'ChangedFiles']

print("--- 5 Dòng đầu tiên có giá trị thiếu ở cột 'ChangedFiles' (Total: 342) ---")
print("-" * 50)
count = 0
for i in range(len(cols['ChangedFiles'])):
    if cols['ChangedFiles'][i] == '':
        print(f"Index {i}:")
        for h in header_to_print:
            print(f"  {h}: {cols[h][i]}")
        print("-" * 50)
        count += 1
        if count >= 5:
            break

print("\n--- Dòng có giá trị thiếu ở cột 'ParentIds' (Total: 1) ---")
print("-" * 50)
for i in range(len(cols['ParentIds'])):
    if cols['ParentIds'][i] == '':
        print(f"Index {i}:")
        for h in header_to_print:
            print(f"  {h}: {cols[h][i]}")
        print("-" * 50)

--- 5 Dòng đầu tiên có giá trị thiếu ở cột 'ChangedFiles' (Total: 342) ---
--------------------------------------------------
Index 0:
  Id: 606b6fd
  ParentIds: c2d2cc2 55a4d01
  AuthorName: M Bussonnier
  AuthorDate: 2025-10-09 11:32:46+02:00
  Subject: Merge pull request #789 from Carreau/master-main
  ChangedFiles: 
--------------------------------------------------
Index 4:
  Id: ecf8996
  ParentIds: 030509a 5e10953
  AuthorName: M Bussonnier
  AuthorDate: 2025-10-08 13:39:18+02:00
  Subject: Merge pull request #767 from jupyter/dependabot/github_actions/dot-github/workflows/actions/download-artifact-4.1.7
  ChangedFiles: 
--------------------------------------------------
Index 24:
  Id: 3dcdce3
  ParentIds: 2f54b80 8806423
  AuthorName: Vidar Tonaas Fauske
  AuthorDate: 2023-11-10 19:18:44+00:00
  Subject: Merge pull request #734 from jupyter/dependabot/npm_and_yarn/axios-1.6.1
  ChangedFiles: 
--------------------------------------------------
Index 26:
  Id: 2f54b80
  ParentId

YOUR ANSWER HERE: *Sau khi xem xét các dòng có giá trị thiếu, ta có thể kết luận:*

1. **Cột "ChangedFiles" (Thiếu: 342 dòng, chiếm 15.914%):**

- Hầu hết các dòng thiếu giá trị `ChangedFiles` là các merge commits (các commit có `Subject` chứa "Merge pull request" hoặc "Merge branch" và thường có 2 hoặc nhiều hơn `ParentIds`).

- Lý do: Khi sử dụng lệnh `git log` với cờ `--name-only`, Git thường không liệt kê các tệp đã thay đổi cho các commit hợp nhất trừ khi có tùy chọn diff đặc biệt, dẫn đến trường này bị trống.

2. **Cột "ParentIds" (Thiếu: 1 dòng, chiếm 0.047%):**

- Dòng thiếu giá trị `ParentIds` là root commit (commit gốc) của repository.

- Lý do: Theo định nghĩa, commit đầu tiên trong lịch sử Git không có commit cha, do đó trường `ParentIds` bị rỗng.

---

## Đưa ra câu hỏi có ý nghĩa cần trả lời

Sau khi khám phá dữ liệu, ta đã hiểu hơn về dữ liệu. Bây giờ, ta hãy xem thử có câu hỏi nào có ý nghĩa mà có thể được trả lời bằng dữ liệu này không.

Các câu hỏi có thể có là: 
- *Câu hỏi 1: trong năm 2021, ai là người có nhiều commit nhất, ai là người có nhiều commit nhì, ...?* \
Tìm câu trả lời cho câu hỏi này để làm gì? \
Hmm ... Chẳng hạn để khen thưởng
- *Câu hỏi 2: commit nào là commit cuối cùng (xét trên "AuthorDate") đã thay đổi file "nbdime/webapp/templates/difftool.html"?* \
Tìm câu trả lời cho câu hỏi này để làm gì? \
Hmm ... Chẳng hạn để đổ tội cho tác giả của commit đó ;-)

---

## Tiền xử lý (nếu cần) + phân tích dữ liệu để trả lời cho câu hỏi 1 (1đ)

Nhắc lại câu hỏi 1: *trong năm 2023, ai là người có nhiều commit nhất, ai là người có nhiều commit nhì, ...?*

Bạn sẽ lưu kết quả vào biến `wanted_people`. Biến này là một dictionary, mỗi phần tử ứng với một người mà có commit trong năm 2023, key là tên của người đó, value là số lượng commit của người đó. Dictionary này được sort theo value giảm dần.

In [18]:
# YOUR CODE HERE
wanted_people = {}

for i in range(len(cols['AuthorDate'])):
    date = cols['AuthorDate'][i]
    # Lọc các commit trong năm 2023
    if date.year == 2023:
        name = cols['AuthorName'][i]
        wanted_people[name] = wanted_people.get(name, 0) + 1

# Sắp xếp dictionary theo value (số lượng commit) giảm dần
wanted_people = dict(sorted(wanted_people.items(), key=lambda item: item[1], reverse=True))

In [19]:
# TEST
correct_wanted_people = {'Vidar Tonaas Fauske': 62,
                         'Frédéric Collonval': 31,
                         'Florence Haudin': 18,
                         'github-actions[bot]': 14,
                         'fcollonval': 4,
                         'dependabot[bot]': 4,
                         'HaudinFlorence': 4,
                         'krassowski': 3,
                         'Michał Krassowski': 3,
                         'Chih-Hsuan Yen': 2,
                         'Angus Hollands': 1,
                         'Min RK': 1,
                         'Johan Mabille': 1,
                         'Saiwing Yeung': 1,
                         'Cory Gwin': 1}
assert wanted_people == correct_wanted_people

---

## Tiền xử lý (nếu cần) + phân tích dữ liệu để trả lời cho câu hỏi 2 (2đ)

Nhắc lại câu hỏi 2: *commit nào là commit cuối cùng (xét trên "AuthorDate") đã thay đổi file "nbdime/webapp/templates/difftool.html"?*

Ta thống nhất: không xét các commit "merge pull request" vì các commit này không có thông tin về "ChangedFiles".

Bạn lưu kết quả vào biến `wanted_commit`. Biến này là một dictionary, trong đó mỗi phần tử ứng với một thông tin của commit, key là tên cột, value là giá trị tương ứng.

In [20]:
# YOUR CODE HERE
latest_date = None
wanted_commit = {}

target_file = "nbdime/webapp/templates/difftool.html"
header_list = list(cols.keys()) # Lấy danh sách tên cột để tạo dictionary kết quả

for i in range(len(cols['ChangedFiles'])):
    subject = cols['Subject'][i]
    changed_files = cols['ChangedFiles'][i]
    author_date = cols['AuthorDate'][i]
    
    # 1. Loại bỏ các commit merge request (theo thống nhất)
    if "Merge " in subject:
        continue
        
    # 2. Kiểm tra xem commit có thay đổi file mục tiêu không
    # ChangedFiles là chuỗi, dùng split để tạo danh sách file
    files_changed_list = changed_files.split(',')
    
    if target_file in files_changed_list:
        # 3. So sánh ngày và cập nhật commit mới nhất
        if latest_date is None or author_date > latest_date:
            latest_date = author_date
            
            # Cập nhật wanted_commit với tất cả các thông tin cột
            wanted_commit = {
                h: cols[h][i] for h in header_list
            }

In [21]:
# TEST
correct_wanted_commit = {'Id': 'd39f45a',
 'ParentIds': '8ebbc6e',
 'AuthorName': 'Frédéric Collonval',
 'AuthorEmail': 'fcollonval@users.noreply.github.com',
 'AuthorDate': datetime.datetime(2023, 10, 20, 23, 20, 31, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200))),
 'Subject': 'Do not collapse editor lines in single editor (#719)',
 'ChangedFiles': 'nbdime/webapp/templates/compare.html,nbdime/webapp/templates/diff.html,nbdime/webapp/templates/difftool.html,nbdime/webapp/templates/merge.html,nbdime/webapp/templates/mergetool.html,packages/nbdime/src/common/mergeview.ts,ui-tests/data/merge_test6/center.ipynb,ui-tests/data/merge_test6/left.ipynb,ui-tests/data/merge_test6/right.ipynb,ui-tests/package-lock.json,ui-tests/tests/nbdime-merge-test6.spec.ts,ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-linux.png,ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-win32.png'}
assert wanted_commit == correct_wanted_commit