--C1
SELECT GV.HOTEN,
(SELECT COUNT(DISTINCT TG.MADT)
FROM THAMGIADT TG JOIN DETAI DT ON
DT.MADT = TG.MADT
WHERE TG.MAGV = GV.MAGV AND
DT.NGAYKT < GETDATE() AND
TG.KETQUA IS NULL) SODTQUAHAN,
SUM(KINHPHI) TONGKINHPHI
FROM GIAOVIEN GV  JOIN (SELECT DISTINCT TG.MADT,KINHPHI, MAGV,YEAR(DT.NGAYBD) NAM
						FROM THAMGIADT TG JOIN DETAI DT
						ON DT.MADT = TG.MADT) TG
ON TG.MAGV = GV.MAGV 
GROUP BY GV.MAGV, GV.HOTEN, NAM
--C2
--KQ: GV HTTT
--C: DT DO TRUONGKHOA CN
--BC: THAM GIA
SELECT KQ.*
FROM GIAOVIEN KQ JOIN BOMON BM ON BM.MABM = KQ.MABM
WHERE BM.TENBM = N'HỆ THỐNG THÔNG TIN'
AND NOT EXISTS (SELECT MADT
				FROM DETAI C JOIN KHOA K
				ON C.GVCNDT = K.TRUONGKHOA
				EXCEPT
				SELECT MADT
				FROM THAMGIADT BC
				WHERE BC.MAGV = KQ.MAGV)
--C3:
GO
CREATE OR ALTER FUNCTION UF_3
	(@MABM NVARCHAR(5))
RETURNS INT
AS
BEGIN
	IF @MABM NOT IN (SELECT MABM FROM BOMON)
		RETURN -1
	RETURN (SELECT COUNT(*)
			FROM GIAOVIEN
			WHERE MABM = @MABM)
END
--
GO
PRINT DBO.UF_3('HTTT')
GO
--C4:
CREATE OR ALTER PROC USP_4
	@MAGV VARCHAR(10),
	@HOTEN NVARCHAR(30),
	@PHAI NVARCHAR(10),
	@NGSINH DATE,
	@DIACHI NVARCHAR(100),
	@GVQLCM NVARCHAR(10),
	@MABM NVARCHAR(10),
	@KQ INT OUT
AS
	IF @MAGV IN (SELECT MAGV FROM GIAOVIEN)
	BEGIN
		SET @KQ = -1
		RETURN
	END
	IF @MABM NOT IN (SELECT MABM FROM BOMON)
	OR DBO.UF_3(@MABM) > 30
	BEGIN
		SET @KQ = -1
		RETURN
	END
	IF @GVQLCM NOT IN (SELECT MAGV FROM GIAOVIEN)
		SET @GVQLCM = (SELECT TRUONGBM
						FROM BOMON
						WHERE MABM = @MABM)
	IF @HOTEN IS NULL
	BEGIN
		SET @KQ = -1
		RETURN
	END
	
	INSERT GIAOVIEN (MAGV, HOTEN, PHAI,NGSINH,DIACHI,GVQLCM,MABM)
	VALUES (@MAGV,@HOTEN,@PHAI,@NGSINH,@DIACHI,@GVQLCM,@MABM)

	IF @@ERROR = 0
		SET @KQ = 0
	ELSE
		SET @KQ = -1
GO
DECLARE @KQ INT
EXEC USP_4 '112','AAA','NAM','4/4/2000','DIA CHI','001','HTTT',@KQ OUT
PRINT @KQ